version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  go-dependency-check:
    container_name: go-dependency-check
    build:
      context: .
    restart: on-failure
    ports:
      - "8181:8181"
    environment:
      - PORT=8181
      - REDIS=redis:6379
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:

volumes:
  redis-data:
